apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: narendra7306/sr-node:17
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: srcred
